apiVersion: v1
kind: Service
metadata:
  name: tf-serving-traffic-sign-classification-model
spec:
  selector:
    app: tf-serving-traffic-sign-classification-model
  ports:
  - port: 8500
    targetPort: 8500