# Streamlit
FROM python:3.10-slim

WORKDIR /app

COPY requirements.streamlit.txt .
RUN pip install -r requirements.streamlit.txt

COPY app.py .
COPY predict_service_functions.py .

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]